name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create project
        run: |
          flutter create --platforms=android --org pl.matematyka --project-name matematyka .
          rm -rf test

      - name: Create app
        run: |
          cp .github/workflows/app.dart lib/main.dart 

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Matematyka-Flutter-APK
          path: build/app/outputs/flutter-apk/app-release.apk
